### PR TITLE
Updated to use latest javaparser and Microsoft.CodeAnalysis libraries

### PR DESCRIPTION
**Pull request by ChristopherHaws**
Updated the project to use javaparser 3.0.0

Also, I removed the deprecated Roslyn nuget packages and replaced them with the latest Microsoft.CodeAnalysis packages.

### CODE REVIEW

**Comment by paulirwin** [comment]
This is awesome :smiley: thank you!

Minor nitpick: can you use 4 spaces instead of tabs? That caused a lot of lines to change that otherwise wouldn't need to, and it doesn't match the existing spacing. Sorry to be a pain!

**Comment by ChristopherHaws** [comment]
Sure, I can use spaces. Did you want me to change all of the files I modified and squash my commits?

**Comment by paulirwin** [comment]
No need to squash but if you can "format document" on those files to convert to spaces that would be appreciated. Thanks!!

**Comment by ChristopherHaws** [comment]
Done! :)

**Comment by paulirwin** [comment]
Awesome, thanks!

**Comment by paulirwin** [comment]
@ChristopherHaws now that JavaParser supports 1.8, any interest in adding a LambdaExpressionVisitor? :smile:

**Comment by ChristopherHaws** [comment]
For sure! Right now I am playing around with getting comments to be ported. After that, I could take a look. :)

**Pull request merged**
