### PR TITLE
Use new interface type names as method parameter type names

### PR DESCRIPTION
**Pull request by VahidN**
Currently the new interface type names (starting with "I") are not used as method parameter type names. This PR fixes this issue.

### CODE REVIEW

**Comment by paulirwin** [comment]
@VahidN If you can kindly address the nullability warnings I'll get this merged, and thanks again for the contribution!

Also I'll fix the test CI issue, you can ignore that part.

**Comment by paulirwin** [comment]
@VahidN Disabled the attempt at running unit tests during the build, GH Actions doesn't like .NET 5 anymore. I am working on upgrading to .NET 6 with the new version of IKVM at which point we should be able to re-enable that. But in the meantime, your next PR push with those fixes should not have a problem with unit tests anymore.

**Comment by VahidN** [comment]
> @VahidN If you can kindly address the nullability warnings I'll get this merged, and thanks again for the contribution!

I fixed the nullability warnings.

**Comment by paulirwin** [comment]
@VahidN 😮 whoa, I only meant the warnings with your changes 😄 this will take me a bit longer to review, but I appreciate you doing that!

**Comment by paulirwin** [comment]
@VahidN Thanks for these changes, but if you can please do not add any more commits to this PR 😄 I need to review it and it's easier if it's not a moving target. We can do several more smaller PRs if needed after this one. Sorry for the delay, but thanks again for your contribution!

**Review by paulirwin — APPROVED** [review]

**Comment by paulirwin** [comment]
@VahidN Merged, thanks! If you can please make sure to use a separate branch for each PR (i.e. issue/123) going forward and keep them smaller, that'll help me merge faster. Thanks!

**Pull request merged**
