### PR TITLE
Applied ~100 suggested code fixes + 2 refactorings

### PR DESCRIPTION
**Pull request by OJacot-Descombes**
Code fixes:
- Consecutive braces must not have blank line between them (1 x)
- Convert to file-scoped namespace (~70 x)
- Index can be simplified (1 x)
- Mark assemblies with NeutralResourcesLanguageAttribute
- Member 'xy' does not access instance data and can be marked as static (2 x)
- Naming rule violation: Missing prefix: '_' (1 x)
- Null check can be simplified (4 x)
- Substring can be simplified (5 x)
- Use framework type (~10 x)
- Use pattern matching (1 x)
- Use 'StringBuilder.Append(char)' instead of 'StringBuilder.Append(string)' (2 x)
- Use 'switch' expression (2 x)
- Using directives must be placed outside of a namespace declaration (3 x)

Refactorings:
- Convert to raw string (2 x)

### CODE REVIEW

**Comment by paulirwin** [comment]
Thanks for this, but note the failing CI build. Also this might take me a bit to review due to the size, so please forgive any delays.

**Comment by OJacot-Descombes** [comment]
I am using a current version Visual Studio 2022 with C# 11. It looks like the build system on Github is using an older version of C#.

**Comment by paulirwin** [comment]
Yes, that's correct. We currently have to target .NET 5 still as support for .NET 6 in IKVM is still in progress. Fortunately there's been some great activity on that project in that regard (including macOS arm64 support), but we might have to wait on that to be complete.

**Comment by wasabii** [comment]
FYI, IKVM's current version runs perfectly fine in .NET 6 and beyond, including 8. The assemblies need to compile targeting 3.1. But 3.1 assemblies run in later CLRs just fine.

**Comment by OJacot-Descombes** [comment]
With the exception of some features depending on CLR support, the C# version does not depend on the Framework version. I use C# 11 features with .NET 4.x with no problems.

**Comment by paulirwin** [comment]
There are several aspects to this conversation and everyone is correct in certain ways 😄 

Here's the build output of the CLI app targeting .NET 5 and built with the .NET 7 SDK:
```
~/git/JavaToCSharp on master λ dotnet build --property WarningLevel=0 /clp:ErrorsOnly ./JavaToCSharpCli/JavaToCSharpCli.csproj
MSBuild version 17.5.0+6f08c67f3 for .NET

Build succeeded.
    9 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.65
~/git/JavaToCSharp on master λ dotnet --version
7.0.202
```

Here's the output when the projects target .NET 6 and upgrading IKVM to the latest 8.6.2:
```
~/git/JavaToCSharp on feature/net6 ● ~1 λ dotnet build --property WarningLevel=0 /clp:ErrorsOnly ./JavaToCSharpCli/JavaToCSharpCli.csproj
MSBuild version 17.5.0+6f08c67f3 for .NET
/Users/paulirwin/.nuget/packages/ikvm.msbuild/8.6.2/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(25,9): error MSB4044: The "IkvmGetReferenceAssemblies" task was not given a value for the required parameter "ToolPath". [/Users/paulirwin/git/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]

Build FAILED.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.96
```

I've tried adding the JDK image and that didn't seem to help. @wasabii if you have any guidance here that would be appreciated.

I can get it to build targeting .NET 6 while keeping IKVM on v8.1, but when I run the unit tests I get this exception:
```
Error Message:
   System.TypeLoadException : Could not load type 'System.Reflection.Emit.MethodToken' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Stack Trace:
     at com.github.javaparser.JavaParser.parse(InputStream in, Charset encoding, Boolean considerComments)
   at com.github.javaparser.JavaParser.parse(InputStream in)
   at JavaToCSharp.JavaToCSharpConverter.ConvertText(String javaText, JavaConversionOptions options) in /Users/paulirwin/git/JavaToCSharp/JavaToCSharp/JavaToCSharpConverter.cs:line 32
   at JavaToCSharp.Tests.IntegrationTests.TestCommentsCanBeConverted(String filePath) in /Users/paulirwin/git/JavaToCSharp/JavaToCSharp.Tests/IntegrationTests.cs:line 16
```

When targeting .NET 5, the unit tests currently fail on macOS but that's because of a `\r\n` vs `\n` line ending difference that I need to fix, not because of an error like the above. The unit test code successfully runs, just an assertion fails. I am assuming they pass on Windows currently but haven't put in the effort to validate that recently.

So I am clearly missing something to say that IKVM on .NET 6 works as-is, at least with this project... I was hoping that the IKVM .NET 6 upgrade would solve that. Maybe fixing the ToolPath error that I don't get on IKVM v8.1 would resolve all of this without having to wait on that?

So that is why we can't upgrade the projects to .NET 6 currently in order to support some of those newer language features. If there are compiler features that don't require .NET 6 runtime support that you'd like to use in the meantime I'm certainly open to that and will merge this PR once the CI build succeeds. 

Thanks again y'all for your help in improving this project!

**Comment by paulirwin** [comment]
Searching for "ToolPath" in IKVM issues brought me to this one, which is bringing back some memories that I've seen this before: https://github.com/ikvmnet/ikvm/issues/271

It seems like we might need to reopen this? It is definitely failing on macOS arm64 for me.

**Comment by paulirwin** [comment]
I'm a little unclear about what you mean by "Was it using IKVM at all?" - the JavaToCSharp project depends on IKVM as a library because the dll (in the lib folder) built from the jar depends on IKVM. So there's no way for us to not use IKVM at all, AFAIK.

If you mean are we using IKVM to build the DLL upon build, the answer is no. I'm using the precompiled DLL. Is there a backwards-compatibility issue at play here because of the version of IKVM the DLL was compiled with?

If there were no backwards compatibility concern, I would infer that we could run IKVM fine on osx-arm64, which I believe is what I'm attempting to do here. Let me know if my understanding is incorrect, thanks!

**Comment by wasabii** [comment]
Well there is def a backwards compatibility issue. Assemblies generated with one version of IKVM shouldn't be used along with another version of IKVM. The generated assemblies consume types within the runtime and base class library. And that API hasn't been stable.

You can generate the assembly on one machine and move it to osx-arm64 and it should work fine. It's just the build tools: ikvmc, and the MSBuild integration, can't work.

**Comment by wasabii** [comment]
The whole thing also apparently works fine on OS X inside Rosetta, or so I've heard.

**Comment by paulirwin** [comment]
Thanks for confirming that suspicion. I'll attempt to rebuild the dll on a Windows x64 machine against latest IKVM.

Also, I'd be happy to help test your macOS arm64 work when it's ready for testing, just let me know. Thanks again for your hard work on that project!

**Comment by wasabii** [comment]
Remember: you gotta build at least two. One for .NET framework, and another for Core.

And consider building these by hand a hack that you have to fix later. Once we get the build tools working on OS X, you should switch to using them. And, if your dependent library is on Maven, you should use IKVM.Maven.Sdk instead. But you need OS X ARM64 support to run all that on OS X ARM64.

**Comment by OJacot-Descombes** [comment]
The only compilation errors related to my pull request are due to using raw string literals in a unit test. Those could easily be converted back to verbatim strings. The advantage of raw string literals is that the multi-line string can be indented nicely along with the code.

This is the source (shortened with "..."):
```
public class ConvertInterfaceTests
{
    [Fact]
    public void Verify_Method_Param_Types_Use_New_Interface_Name_Types()
    {
        var javaCode = """
            import com.github.javaparser.resolution.Context;
            import com.github.javaparser.resolution.Test;
...
            """;
        var options = new JavaConversionOptions { StartInterfaceNamesWithI = true };
        options.WarningEncountered += (_, eventArgs)
                                          => Console.WriteLine("Line {0}: {1}", eventArgs.JavaLineNumber, eventArgs.Message);
        var parsed = JavaToCSharpConverter.ConvertText(javaCode, options);

        var expectedCSharpCode = """
            using Com.Github.Javaparser.Resolution;
            using System;
...
            }
            """;

        Assert.Equal(expectedCSharpCode, parsed);
    }
}
```

This unit test itself also fails. The produced output has an additional "using System.Collections.ObjectModel;" which is not expected.

Since I did not change these usings, another pull request or commit must have added it.

**Comment by paulirwin** [comment]
Would you mind fixing the unit test as part of this PR? That would be greatly appreciated!

**Comment by paulirwin** [comment]
Actually scratch that, I'll fix the unit test as part of the .NET 6 upgrade. I have those building and running in the Actions build now.

Thanks for your help @wasabii, I will have .NET 6 support merged soon.

**Comment by paulirwin** [comment]
@OJacot-Descombes Are you planning on resubmitting a PR in a separate branch? I look forward to improving the code with your PR. My apologies for any inconvenience around the .NET 6 upgrade 😦

**Comment by OJacot-Descombes** [comment]
Oh sorry, I missed that with the separate branch.

A new build error is appearing on github because of a failing unit test. The same test runs fine on my system (why?):
```
[xUnit.net 00:00:00.96]     JavaToCSharp.Tests.ConvertInterfaceTests.Verify_Method_Param_Types_Use_New_Interface_Name_Types [FAIL]
  Failed JavaToCSharp.Tests.ConvertInterfaceTests.Verify_Method_Param_Types_Use_New_Interface_Name_Types [696 ms]
  Error Message:
   Assert.Equal() Failure: Strings differ
                                     ↓ (pos 247)
Expected: ···"\n    {\r\n        bool IsArray();\r\n    }\r\n\r"···
Actual:   ···"\n    {\r\n        boolean IsArray();\r\n    }"···
                                     ↑ (pos 247)
  Stack Trace:
     at JavaToCSharp.Tests.ConvertInterfaceTests.Verify_Method_Param_Types_Use_New_Interface_Name_Types() in D:\a\JavaToCSharp\JavaToCSharp\JavaToCSharp.Tests\ConvertInterfaceTests.cs:line 60
```

**Pull request closed without merging**
