### PR TITLE
Add simple enumeration type code conversions

### PR DESCRIPTION
**Pull request by tupunco**
- enum `args-body` to `code Comment`
- enum `method-body` to `code Comment`

## Design goals:
- Implement simplest `enumeration type code` conversion
- Unable to convert content (args-body/method-body) to `code comments`:

### src-JAVA
```java
package org.apache.ibatis.session;

public enum AutoMappingUnknownColumnBehavior {
  /**
   * Output warning log.
   * Note: The log level of {@code 'org.apache.ibatis.session.AutoMappingUnknownColumnBehavior'} must be set to {@code WARN}.
   */
  WARNING (-1),

  FAILING,

  /**
   * Do nothing (Default).
   */
  NONE {
    @Override
    public void doAction(MappedStatement mappedStatement, String columnName, String property, Class<?> propertyType) {
      // do nothing
    }
  };


  /**
   * Perform the action when detects an unknown column (or unknown property type) of automatic mapping target.
   * @param mappedStatement current mapped statement
      */
  public abstract void doAction(MappedStatement mappedStatement, String columnName, String propertyName, Class<?> propertyType);

  /**
   * build error message.
   */
  private static String buildMessage(MappedStatement mappedStatement, String columnName, String property, Class<?> propertyType) {
    return new StringBuilder("Unknown column is detected on '")
      .append(mappedStatement.getId())
      .append("' auto-mapping. Mapping parameters are ")
      .append("[")
      .append("columnName=").append(columnName)
      .append(",").append("propertyName=").append(property)
      .append(",").append("propertyType=").append(propertyType != null ? propertyType.getName() : null)
      .append("]")
      .toString();
  }

  private static class LogHolder {
    private static final Log log = LogFactory.getLog(AutoMappingUnknownColumnBehavior.class);
  }

}
```
### result-C#
```csharp
namespace Org.Apache.Ibatis.Session
{
    public enum AutoMappingUnknownColumnBehavior
    {
        /// <summary>
        /// Output warning log.
        /// Note: The log level of {@code 'org.apache.ibatis.session.AutoMappingUnknownColumnBehavior'} must be set to {@code WARN}.
        /// </summary>
        // /**
        //    * Output warning log.
        //    * Note: The log level of {@code 'org.apache.ibatis.session.AutoMappingUnknownColumnBehavior'} must be set to {@code WARN}.
        //    */
        // WARNING(-1)
        WARNING,
        FAILING,
        /// <summary>
        /// Do nothing (Default).
        /// </summary>
        // /**
        //    * Do nothing (Default).
        //    */
        // NONE {
        // 
        //     @Override
        //     public void doAction(MappedStatement mappedStatement, String columnName, String property, Class<?> propertyType) {
        //     // do nothing
        //     }
        // }
        // 
        NONE 

        // --------------------
        // TODO enum body members
        // /**
        //    * Perform the action when detects an unknown column (or unknown property type) of automatic mapping target.
        //    * @param mappedStatement current mapped statement
        //       */
        // public abstract void doAction(MappedStatement mappedStatement, String columnName, String propertyName, Class<?> propertyType);
        // /**
        //    * build error message.
        //    */
        // private static String buildMessage(MappedStatement mappedStatement, String columnName, String property, Class<?> propertyType) {
        //     return new StringBuilder("Unknown column is detected on '").append(mappedStatement.getId()).append("' auto-mapping. Mapping parameters are ").append("[").append("columnName=").append(columnName).append(",").append("propertyName=").append(property).append(",").append("propertyType=").append(propertyType != null ? propertyType.getName() : null).append("]").toString();
        // }
        // private static class LogHolder {
        // 
        //     private static final Log log = LogFactory.getLog(AutoMappingUnknownColumnBehavior.class);
        // }
        // --------------------
    }
}
```

### CODE REVIEW

**Comment by tupunco** [comment]
> Earlier this said that there was some work still to be done, do you think this is ready to merge?

The previous two problems have been solved. 

## Some ideas:
- It feels like a `option` is needed to determine whether `unrecognized code` should be `code comment` output.
- This `option` can be `turned off` when the `USER` does not need to focus on `unrecognized code`, and will be used in `Other Convert` tasks, such as `java-Annotations-Convert` (this PR will be submitted later) .

**Comment by tupunco** [comment]
> > Earlier this said that there was some work still to be done, do you think this is ready to merge?
> 
> The previous two problems have been solved.
> 
> ## Some ideas:
> * It feels like a `option` is needed to determine whether `unrecognized code` should be `code comment` output.
> * This `option` can be `turned off` when the `USER` does not need to focus on `unrecognized code`, and will be used in `Other Convert` tasks, such as `java-Annotations-Convert` (this PR will be submitted later) .

OK, All the content of this PR has been completed.

**Comment by paulirwin** [comment]
@tupunco Thanks! I'll take a look at this soon.

**Comment by paulirwin** [comment]
I'm preparing a 2.1 release with this change. My sincerest apologies for the delay.

**Pull request merged**
