### PR TITLE
Added more missing features

### PR DESCRIPTION
**Pull request by VahidN**
I was testing this project on the huge Java code base and now it runs without a glitch! Here are the required changes.

### CODE REVIEW

**Comment by paulirwin** [comment]
Fantastic work, thanks! Looking forward to the Java 8+ support. Will review and get back to you.

**Comment by Rubenisme** [comment]
I also added a few features last year: https://github.com/Rubenisme/JavaToCSharp/commits/master
Maybe you can include the ones you don't have yet.

**Comment by paulirwin** [comment]
Thanks for reminding me to review this PR. I just pulled and ran on a simple example of a lambda but i'm getting a null reference exception. Will dig into it a bit.

**Comment by paulirwin** [comment]
Thanks for the contribution @VahidN! I've merged this PR. I noticed one issue that is possibly a bug in Roslyn, not sure, but with the basic example below (pulled from a random blog post) it generates an extra semicolon in the output. I'll file an issue for that if anyone wants to tackle it.

```Java
class Test 
{ 
    public static void main(String args[]) 
    { 
        // lambda expression to implement above 
        // functional interface. This interface 
        // by default implements abstractFun() 
        FuncInterface fobj = (int x)->System.out.println(2*x); 
  
        // This calls above lambda expression and prints 10. 
        fobj.abstractFun(5); 
    } 
} 
```

Output:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyApp
{
    class Test
    {
        public static void Main(string[] args)
        {
            FuncInterface fobj = (int x) => System.out_renamed.Println(2 * x);
            ;
            fobj.AbstractFun(5);
        }
    }
}
```

Also the NRE was something unrelated to this PR, if Include Namespace is checked and the input doesn't have a package name, it failed. Fixed by coalescing that to "MyApp".

**Comment by paulirwin** [comment]
@Rubenisme I'd be happy to review a PR for your changes as well if you'd like to submit them. Thanks!

**Pull request merged**
